release:
  prerelease: auto # this should detect a release candidate and mark it as pre-release in GitHub

builds:
  - id: default
    binary: doki
    flags:
      - -tags
      - netgo release
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      # gitTag set from a generated file (see ./tag_release.sh)
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

archives:
  - id: default
    builds:
      - default
    name_template: "doki_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    files:
      - none*

checksum:
  name_template: "doki_checksums.txt"